### ISSUE TITLE
Move Docker files over to make-haros-easy

### ISSUE THREAD

**Issue by git-afsantos** [git-afsantos/haros#104]
Docker is just a convenience to install and set up HAROS.
Take the Docker files out of this repository, and move them over to the new convenience repository, [make-haros-easy](https://github.com/git-afsantos/make-haros-easy).

**Comment by ipa-nhg** [comment]
A suggestion: https://github.com/git-afsantos/make-haros-easy/pull/1

If the previous PR get merged, the folder docker of this repository should be removed.

**Comment by git-afsantos** [comment]
Will do. Thanks for the PR!
