### ISSUE TITLE
To which extent is ROS2 supported?

### ISSUE THREAD

**Issue by ivanperez-keera** [git-afsantos/haros#117]
Hi,

To which extent is ROS2 supported?

I've seen a few issues, PRs and commits mentioning ROS 2, but it is unclear to me (I'm no expert).

Thanks

**Comment by git-afsantos** [comment]
Hello there,

In the current version, support is practically non-existent. It might be able to detect ROS2 packages and run the general-purpose C++/Python analysis tools, but not the more advanced features like model extraction and automatic testing.

**Comment by ivanperez-keera** [comment]
Thanks, and thank you for responding to my email as well.
