### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by git-afsantos** [git-afsantos/haros#26]
Python 2.7 will reach the end of its life on January 1st, 2020.

**Comment by asmodehn** [comment]
Hi, I m just dropping a note here to give a pointer to https://wily.readthedocs.io/en/latest/

**Comment by git-afsantos** [comment]
Thanks for the pointer @asmodehn. I was not aware of this tool yet.

**Comment by max-krichenbauer** [comment]
I ran a quick update of the current HAROS version from to Python3 to see if I would run into any problems:
https://github.com/max-krichenbauer/haros/tree/python3
I did not have any issues - everything seems to be running smoothly.

**Comment by git-afsantos** [comment]
@max-krichenbauer Thanks for trying it out! I figured most of the changes would be due to the iterators and some imports, but I am glad that there is some confirmation now.

**Comment by mikaelarguedas** [comment]
I'm interested in using this package in ROS Noetic (Python3 only). @git-afsantos is Python3 support something that is in the roadmap of haros ? do you foresee any blocker for this moving forward? I'm not familiar with haros but can maybe give a hand in the porting/testing if it's something that you're interested in supporting/releasing in Noetic.

**Comment by git-afsantos** [comment]
@mikaelarguedas Python3 is definitely going to be added sometime in the future (soon™).
As you can see from the comment and preliminary experiments of Max, above, it seems that most of HAROS is already compatible.

One of the pending goals is to add support for ROS2, which also requires Python3, so I will have to do it.
I am just getting done with the last stages of my thesis, and afterwards I will be focusing more on the tool.

**Comment by git-afsantos** [comment]
@mikaelarguedas I have gone through the code of HAROS, [bonsai](https://github.com/git-afsantos/bonsai), and some HAROS plugins ([1](https://github.com/git-afsantos/haros_plugins), [2](https://github.com/git-afsantos/haros-plugin-model-ged), [3](https://github.com/git-afsantos/haros-plugin-pbt-gen), [4](https://github.com/git-afsantos/haros-plugin-pyflwor)) to try and make them compatible with Python 3. After running a few preliminary tests, I think most of the issues should be gone.

In any case, if you are willing, you could try out running HAROS from source, and let me know if you run into any problems on your machine. Be sure to check out the [`dev-py3-support` branch](https://github.com/git-afsantos/haros/tree/dev-py3-support).

If everything goes well, I should be able to open a PR and make a release for this version.

**Comment by mikaelarguedas** [comment]
That's awesome thanks! I'll give it a try over the weekend

**Comment by mikaelarguedas** [comment]
@git-afsantos I could get a python3 version running based on the `dev-py3-support` with a couple changes. The diff can be seen at https://github.com/git-afsantos/haros/compare/dev-py3-support...mikaelarguedas:dev-py3-support?expand=1
The main changes are making the dockerfile work on ROS Noetic and Focal system dependencies as well as fixing crashes due to missing arguments in the full parser

**Comment by git-afsantos** [comment]
Thanks for your contribution, @mikaelarguedas ! :+1:

**Comment by ipa-hsd** [comment]
I needed some small changes for @max-krichenbauer's `python3` branch to work: https://github.com/max-krichenbauer/haros/pull/1. I have not tested https://github.com/git-afsantos/haros/tree/dev-py3-support yet.

Should `pip3 install haros` install one of these 2 branches?

**Comment by git-afsantos** [comment]
No, @ipa-hsd.
These branches were not released yet, it must be cloned from the source. I should probably include the changes in the next release, though.

**Comment by git-afsantos** [comment]
The changes to support Python 3 have been merged in #109, and released as [HAROS v3.10.4](https://github.com/git-afsantos/haros/releases/tag/v3.10.4) .
If there are further problems or incompatibilities, please report them in a new issue,
