### ISSUE TITLE
No module named bonsai.model

### ISSUE THREAD

**Issue by droter** [git-afsantos/haros#29]
Following the Method 1 install.  I am getting this error:

File "./haros-runner.py", line 24, in <module>
    from haros.haros import main
  File "/home/matt/lawn_tractor_ws/src/haros/haros/haros.py", line 102, in <module>
    from .extractor import ProjectExtractor
  File "/home/matt/lawn_tractor_ws/src/haros/haros/extractor.py", line 34, in <module>
    from bonsai.model import CodeGlobalScope, pretty_str
ImportError: No module named bonsai.model

I have installed the dependencies listed on the README.  Is Bonsai this a separate install?

Thanks for your help,

Matt

**Comment by droter** [comment]
Update:  Method 2 installed bonsai

**Comment by git-afsantos** [comment]
It is a dependency that I forgot to add. Thanks for reminding me, I will fix both the instructions and the dependency list.

In the meantime:

```bash
pip install bonsai-code
```

**Comment by droter** [comment]
Thanks Andre
