### ISSUE TITLE
Melodic Updates

### ISSUE THREAD

**Issue by JWhitleyAStuff** [git-afsantos/haros#52]
Are there currently any plans to support 18.04/Melodic? If so, is there a timeline?

**Comment by git-afsantos** [comment]
Could you be more specific? Is there something that is not working in Melodic? Something related to C++14, perhaps?

I can set up a machine with Melodic to try it out, but in principle most of the tools should work right away.

**Comment by JWhitleyAStuff** [comment]
Mostly it's the version of clang. 3.8 is not available in Ubuntu 18.04.

**Comment by gavanderhoorn** [comment]
re: clang: see #42.

**Comment by JWhitleyAStuff** [comment]
Thanks. I'll continue discussion there.

**Comment by git-afsantos** [comment]
@JWhitleyAStuff Sorry for the late response. I have just posted an update on the other issue (https://github.com/git-afsantos/haros/issues/42#issuecomment-482895476).
