### ISSUE TITLE
Should rosgraph be added to requirements.txt?

### ISSUE THREAD

**Issue by gavanderhoorn** [git-afsantos/haros#64]
That package will probably always be installed when users have ROS installed, but if `requirements.txt` is supposed to capture the Python modules necessary to be able to run haros, then it would seem that `rosgraph` should be listed.

`rospkg` is listed:

https://github.com/git-afsantos/haros/blob/2196db1a34c1e862d7640d6d85eb404319f17048/requirements.txt#L2

On systems with ROS installed, `pip` will probably detect it and decide that the dependency has already been satisfied. On systems without, it will be installed.

**Comment by gavanderhoorn** [comment]
It's used here:

https://github.com/git-afsantos/haros/blob/c2ecbfa432fafcc7adbde543e205439be00f8d2e/haros/launch_parser.py#L30

**Comment by git-afsantos** [comment]
Makes sense to me. Thanks for the PR! :+1:

**Comment by gavanderhoorn** [comment]
It may even be that `rosgraph` is not released on `pypi` :(

I should've checked better (doing too many things at the same time right now).

**Comment by git-afsantos** [comment]
I cannot find it. Unless it is bundled within some other distribution, I think it may not be released individually on PyPI.

**Comment by gavanderhoorn** [comment]
Just checked: it's a ROS package, not a pure Python one.

Submitted #66.

Sorry for the noise and the work.

**Comment by gavanderhoorn** [comment]
It would still be good to have some way of expressing this dependency though.

Perhaps a `try: .. except: ..` around the import would be an idea? That way we at least can print a more user-friendly error message instead of an import error.

**Comment by git-afsantos** [comment]
> Perhaps a `try: .. except: ..` around the import would be an idea? That way we at least can print a more user-friendly error message instead of an import error.

I was thinking about this again. I will make it a lazy import, and provide a warning and a fallback, in case it is missing.

**Comment by gavanderhoorn** [comment]
The fallback is perhaps not necessary, and my use-case is slightly exotic.

Even just a nicer error would be great.

**Comment by git-afsantos** [comment]
Addressed and fixed in #67 and #68 @gavanderhoorn
