### ISSUE TITLE
Can't get the topics in "Models"

### ISSUE THREAD

**Issue by LeiGong-USTC** [git-afsantos/haros#99]
I  just followed the tutorial and used haros to analyse the haros_tutorials, but when i runs the visualisation i can not get any topics in the Models  

![image](https://user-images.githubusercontent.com/61455664/78998972-4743ac80-7b7c-11ea-830e-c019e0c08599.png)
but the demo you show on the https://git-afsantos.github.io/haros/#dashboard can ,so i just don't know what's the problem is  
![image](https://user-images.githubusercontent.com/61455664/78999357-04360900-7b7d-11ea-9b7a-3477d8a92d39.png)

**Comment by git-afsantos** [comment]
What commands did you run?
Did you follow the steps in [Model Extraction](https://github.com/git-afsantos/haros/blob/master/MODEL_EXTRACTION.md)?

In particular, did you compile the code with clang *before* running HAROS, and did you generate a `compile_commands.json` file?

**Comment by LeiGong-USTC** [comment]
the command  is `python haros-runner.py full  -n -p  /path/to/my_index.yaml`
i just use the catkin_make to build and source the devel/setup.bash,but i didn't compile the code with clang,maybe that's the reason ,i will try this ,thanks for your help !

**Comment by LeiGong-USTC** [comment]
I have solved the problem
i compiled the code with clang  but it still didn't work , then i change the `workspace` and `cpp:compile_db`  in ~/.haros/configs.yaml  ,make sure that they are pointing to my workspace directory,however it still didn't work.
finally , i deleted the old haros_tutorials project  in ~/.haros/projects ,  then run the command `python haros-runner.py full -n -p /path/to/my_index.yaml` and the problem solved

**Comment by git-afsantos** [comment]
Good to know! :+1:
